### ISSUE TITLE
Question: when will the mesh scaling fix be included in the release?

### ISSUE THREAD

**Issue by rokusottervanger** [cyberbotics/urdf2webots#171]
I ran into some problems with mesh scaling. After a quick search, I found that in #157 attempts to fix this issue, but it is not merged to master, thus not included in the latest release. When will this be included?

**Comment by omichel** [comment]
The develop branch should be merged into the master branch by the end of June (when we release Webots R2022b). Meanwhile, I would recommend you to apply the patch locally or checkout the source from the develop branch (which is fairly stable).
