### ISSUE TITLE
Improvement of Duplicated Vertices Removal 

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/urdf2webots#20]
For a better performance, the algorithm removing the duplicated vertices in a mesh should be improved:
https://github.com/omichel/urdf2webots/blob/c4ad004eccbd5bf97f3c6b1d31511d0f029e6df2/parserURDF.py#L384
Instead of parsing and removing the duplicated meshes at the same time, this should be done in 3 passes:
  1. Parse the file and add all the vertices.
  2. Loop over all the vertices, check for duplicated vertices and stor the index in a hash table.
  3. Loop the hash table to remove the actual duplicated vertices and update the index accordingly (replace index of removed vertices and shifting of the next indices).

**Comment by BenjaminHug8** [comment]
I am closing this issue as the importer tool does not convert mesh file anymore, Webots does it when parsing WbMesh nodes.
