### ISSUE TITLE
Error during conversion

### ISSUE THREAD

**Issue by SunnyKatyara** [cyberbotics/urdf2webots#23]
I am trying to convert urdf of my robot into webots but its showing following error.

Root link: panda_virtual_link_0
Traceback (most recent call last):
  File "urdf2webots.py", line 138, in <module>
    parserURDF.parseGazeboElement(child, rootLink.name, linkList)
  File "/home/sunny/development/catkinws/src/urdf2webots/parserURDF.py", line 801, in parseGazeboElement
    print('Unsupported "%lf" image format, using "R8G8B8A8" instead.' % imageElement.getElementsByTagName('format')[0].firstChild.nodeValue)
TypeError: float argument required, not unicode

Can you please help me to convert it.

Thank You

**Comment by DavidMansolino** [comment]
Hi, thank you for the bug report.
Which version of Python are you using?
would it be possible for you to share the URDF file?

**Comment by SunnyKatyara** [comment]
I am using 2.7 and i do not know how to share mu URDF here.

**Comment by DavidMansolino** [comment]
You simply have to put it in a zip archive and you can then drag and drop it on the text area.

**Comment by SunnyKatyara** [comment]
[panda.tar.gz](https://github.com/cyberbotics/urdf2webots/files/3635941/panda.tar.gz)

Here is the URDF with all meshes.....

**Comment by DavidMansolino** [comment]
Thank you, we will try it and let you know what is not working.

**Comment by SunnyKatyara** [comment]
Thank You

**Comment by DavidMansolino** [comment]
I just found the cause of the issue, and I have created a patch here: #24 

I checked with your URDF file and it seems to work fine (raw import without any edition):
![panda](https://user-images.githubusercontent.com/2461619/65330749-982d8c80-dbbb-11e9-8d33-56e53e137567.png)

Note also that your URDF file contains some paths `package://tutorial_iros2018/robots/` please replace them by the actual path to your folder (e.g. search and replace in the file `package://tutorial_iros2018/robots/panda` by `home/username/panda`).

Let me know if it woks fine with this patch for you too.

**Comment by SunnyKatyara** [comment]
You used urdf2webots converter? am i right? Just its the issue with path?

**Comment by DavidMansolino** [comment]
Yes, I did use the urdf2webots convert.
Your import fails for two reasons:
  - It need the fix of #24 (to get it simply clone the repository on this branch: `git clone -b fix-error-message https://github.com/cyberbotics/urdf2webots.git`)
  - The paths need to be corrected.

**Comment by SunnyKatyara** [comment]
Thank you. The code is working now. But i am unable locate my file. the output file. Where can i find it normally? Because in the Urdf2webots i can see panda_texture folder but no PORTO folder.

Thank You

**Comment by SunnyKatyara** [comment]
Working. Thank You

**Comment by DavidMansolino** [comment]
Good news!

It will create directly a panda.proto file. you can then copy this file in the `proto` folder of your project and then you will be able to add the robot to your simulation.
